### ISSUE TITLE
[Request] google drive & solidfiles

### ISSUE THREAD

**Issue by PT-Aweh-KangTravel** [yasawibu/yasa-download-helper#1]
http://elsfile.org/lnznn9qlurgn
http://www.solidfiles.com/v/824jXdAkxWeGd
https://docs.google.com/uc?id=1bhlqnZFFWSDH2ORN5RZS7rY6QaSiebG6&export=download

**Comment by yasawibu** [comment]
@alvahn 
Nanti kalau request banyak file hosting lagi, mohon dipisah issue-nya ya.
Kalau jadi satu gini, saya yang kerepotan, karena harus ditambahin semua dulu baru bisa rilis.
Kalau misal dipisah, saya kan bisa selesaikan sebagian yang saya bisa dulu, terus rilis seadanya.
Sisanya bisa di rilis belakangan.

Untuk solidfiles dan google dengan 'format link' di atas sudah jadi.
Kalau ada format link solidfiles atau google yang lain, mohon dishare.

Untuk yang elsfile, masih dalam proses.
Agak ribet soalnya (kadang muncul, kadang enggak tombol downloadnya pas saya buka).
Bisa kasih saya link elsfile alternatif? kalau bisa lebih dari 3 lebih bagus.

Terima kasih.

**Comment by PT-Aweh-KangTravel** [comment]
@yasawibu di oploverz.in gan contoh link elsfilenya

**Comment by yasawibu** [comment]
@alvahn 
Ini issuenya saya split ya.
Yang elsfile makan waktu soalnya.
Sudah nemu caranya, tapi masih butuh waktu buat implementasinya.
