### ISSUE TITLE
[Request] drive.google.com

### ISSUE THREAD

**Issue by PT-Aweh-KangTravel** [yasawibu/yasa-download-helper#4]
https://drive.google.com/uc?id=1Q6E5rHZuJ21_t7BY7bSzvnZlM0mhEDUs&export=download

**Comment by yasawibu** [comment]
Baru support docs.google.com doang soalnya.
Jadi wajar kalau drive.google.com enggak mau.

Untuk project yasa-download-helper mungkin agak slow update-nya, soalnya lagi ada kesibukan.
Jadi mohon kesabarannya.

Terima kasih.

**Comment by yasawibu** [comment]
Done yah.
Thanks atas infonya ^^
